### ISSUE TITLE
NoSuchMethodError: Capabilities.getPlatform()

### ISSUE THREAD

**Issue by faveoled** [scala-js/scala-js-env-selenium#130]
Hitting this error when running `test`:
```
sbt:livechart> test
[error] stack trace is suppressed; run last Test / jsEnv for the full output
[error] (Test / jsEnv) java.lang.NoSuchMethodError: 'org.openqa.selenium.Platform org.openqa.selenium.Capabilities.getPlatform()'
[error] Total time: 0 s, completed Jul 18, 2023, 8:27:09 PM
sbt:livechart> last Test / jsEnv
[error] java.lang.NoSuchMethodError: 'org.openqa.selenium.Platform org.openqa.selenium.Capabilities.getPlatform()'
[error]         at org.openqa.selenium.remote.server.DefaultDriverFactory.platformMatches(DefaultDriverFactory.java:138)
[error]         at org.openqa.selenium.remote.server.DefaultDriverFactory.registerDriverProvider(DefaultDriverFactory.java:126)
[error]         at org.openqa.selenium.remote.server.DefaultDriverFactory.registerDefaults(DefaultDriverFactory.java:114)
[error]         at org.openqa.selenium.remote.server.DefaultDriverFactory.<init>(DefaultDriverFactory.java:84)
[error]         at org.scalajs.jsenv.selenium.SeleniumJSEnv$Config.<init>(SeleniumJSEnv.scala:59)
[error]         at org.scalajs.jsenv.selenium.SeleniumJSEnv$Config$.apply(SeleniumJSEnv.scala:127)
[error]         at org.scalajs.jsenv.selenium.SeleniumJSEnv.<init>(SeleniumJSEnv.scala:14)
[error]         at $ebaa9a7cfd2c95ea0ad3$.$anonfun$$sbtdef$1(/home/user/Dev/Scala/linkchecker-web/build.sbt:9)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:47)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (Test / jsEnv) java.lang.NoSuchMethodError: 'org.openqa.selenium.Platform org.openqa.selenium.Capabilities.getPlatform()'
```
Any ideas?

**Comment by faveoled** [comment]
This was caused by using selenium driver v. 4.x.x while the calling code is v.3.x.x
