### ISSUE TITLE
Browser warnings prevent test execution

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-env-selenium#60]
According to the source of `browserErrors`, it retrieves log messages from the browser and returns severe entries as errors. When errors are present, the plugin shuts down without running the tests.

The problem is that warnings are incorrectly being detected as errors. I have this bogus warning in my `providedJS` (which will eventually be fixed by the React team):

```
webapp-client-project> last webapp-client-project/chrome:loadedTestFrameworks
java.lang.Exception: Errors caught by browser:
file:///tmp/1466387951674-0/setupConsoleCapture.js 13:12 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
    at org.scalajs.jsenv.selenium.SeleniumRunner.run(SeleniumRunner.scala:29)
    at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:66)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60.apply(ScalaJSPluginInternal.scala:738)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60.apply(ScalaJSPluginInternal.scala:721)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (webapp-client-project/chrome:loadedTestFrameworks) java.lang.Exception: Errors caught by browser:
[error] file:///tmp/1466387951674-0/setupConsoleCapture.js 13:12 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
```

Despite this saying `Warning`, it is preventing the execution of tests.

**Comment by sjrd** [comment]
Could you provide a reproduction, please?
